services:
  api:
    image: captaincoordinates/tile-id-api
    build:
      args:
        LOG_LEVEL: debug
      dockerfile: dockerfile.api
    ports:
      - ${TILE_ID_LISTEN_PORT:-8123}:8080
    volumes:
      - ./tile-id-api:/src:ro
  unittest:
    build:
      dockerfile: dockerfile.unittest
    volumes:
      - ./tile-id-api:/src:ro
    profiles:
      - unittest
  integrationtest:
    build:
      dockerfile: dockerfile.integrationtest
    volumes:
      - ./scripts/docker:/tests:ro
    depends_on:
      - api
  validateopenapi:
    build:
      dockerfile: dockerfile.validateopenapi
    volumes:
      - ./tile-id-api/openapi.yml:/openapi/openapi.yml:ro
  mapproxy:
    build:
      dockerfile: dockerfile.mapproxy
    ports:
      - ${MAPPROXY_LISTEN_PORT:-8124}:8080
    volumes:
      - ./mapproxy/config:/mapproxy/config:ro
    depends_on:
      - api
