openapi: 3.0.0
info:
  title: Tile ID API
  description: Simple tile API to support map tile identification across different tiling schemes.
  version: 0.0.1
externalDocs:
  description: Source code, feature requests, and bug reports.
  url: https://github.com/captaincoordinates/tile-id-api
components:
  responses:
    TileResponse:
      description: A PNG or JPEG tile response
      headers:
        X-Tile-Id-Xyz:
          description: The tile's identifier in the XYZ tiling scheme
          schema:
            type: string
        X-Tile-Id-Tms:
          description: The tile's identifier in the TMS tiling scheme
          schema:
            type: string
        X-Tile-Id-Quadkey:
          description: The tile's identifier in the Quadkey tiling scheme
          schema:
            type: string
        X-Tile-Opacty:
          description: The tile's opacity in the format x/255
          schema:
            type: string
        X-Tile-Bounds-Ll84:
          description: The tile's bounds in WGS84 Longitude / Latitude, in JSON format
          schema:
            type: string
            format: json
      content:
        image/png:
          schema:
            type: string
            format: binary
        image/jpeg:
          schema:
            type: string
            format: binary
  parameters:
    z:
      name: z
      in: path
      required: true
      description: zoom level
      schema:
        type: integer
        minimum: 0
        maximum: 25
    x:
      name: x
      in: path
      required: true
      description: x tile column
      schema:
        type: integer
        minimum: 0
    y:
      name: y
      in: path
      required: true
      description: y tile row
      schema:
        type: integer
        minimum: 0
    quadkey:
      name: quadkey
      in: path
      required: true
      description: quadkey ID
      schema:
        type: string
    extension:
      name: extension
      in: path
      required: true
      schema:
        type: string
        enum: [png, jpg, jpeg]
    opacityPercentQueryString:
      name: opacityPercent
      in: query
      required: false
      schema:
        type: integer
        minimum: 0
        maximum: 100
    opacityPercentHeader:
      name: X-Opacity-Percent
      in: header
      required: false
      schema:
        type: integer
        minimum: 0
        maximum: 100

paths:
  /xyz/{z}/{x}/{y}:
    get:
      tags:
        - Tile Requests
      summary: Return a tile in the XYZ tiling schema, default file extension
      parameters:
        - $ref: '#/components/parameters/z'
        - $ref: '#/components/parameters/x'
        - $ref: '#/components/parameters/y'
        - $ref: '#/components/parameters/opacityPercentQueryString'
        - $ref: '#/components/parameters/opacityPercentHeader'
      responses:
        "200":
          $ref: '#/components/responses/TileResponse'
  /xyz/{z}/{x}/{y}.{extension}:
    get:
      tags:
        - Tile Requests
      summary: Return a tile in the XYZ tiling schema
      parameters:
        - $ref: '#/components/parameters/z'
        - $ref: '#/components/parameters/x'
        - $ref: '#/components/parameters/y'
        - $ref: '#/components/parameters/extension'
        - $ref: '#/components/parameters/opacityPercentQueryString'
        - $ref: '#/components/parameters/opacityPercentHeader'
      responses:
        "200":
          $ref: '#/components/responses/TileResponse'
  /tms/{z}/{x}/{y}:
    get:
      tags:
        - Tile Requests
      summary: Return a tile in the TMS tiling schema, default file extension
      parameters:
        - $ref: '#/components/parameters/z'
        - $ref: '#/components/parameters/x'
        - $ref: '#/components/parameters/y'
        - $ref: '#/components/parameters/opacityPercentQueryString'
        - $ref: '#/components/parameters/opacityPercentHeader'
      responses:
        "200":
          $ref: '#/components/responses/TileResponse'
  /tms/{z}/{x}/{y}.{extension}:
    get:
      tags:
        - Tile Requests
      summary: Return a tile in the TMS tiling schema
      parameters:
        - $ref: '#/components/parameters/z'
        - $ref: '#/components/parameters/x'
        - $ref: '#/components/parameters/y'
        - $ref: '#/components/parameters/extension'
        - $ref: '#/components/parameters/opacityPercentQueryString'
        - $ref: '#/components/parameters/opacityPercentHeader'
      responses:
        "200":
          $ref: '#/components/responses/TileResponse'
  /quadkey/:
    get:
      tags:
        - Tile Requests
      summary: Return the root tile in the Quadkey tiling schema, default file extension
      parameters:
        - $ref: '#/components/parameters/opacityPercentQueryString'
        - $ref: '#/components/parameters/opacityPercentHeader'
      responses:
        "200":
          $ref: '#/components/responses/TileResponse'
  /quadkey/.{extension}:
    get:
      tags:
        - Tile Requests
      summary: Return the root tile in the Quadkey tiling schema
      parameters:
        - $ref: '#/components/parameters/extension'
        - $ref: '#/components/parameters/opacityPercentQueryString'
        - $ref: '#/components/parameters/opacityPercentHeader'
      responses:
        "200":
          $ref: '#/components/responses/TileResponse'
  /quadkey/{quadkey}:
    get:
      tags:
        - Tile Requests
      summary: Return a non-root tile in the Quadkey tiling schema, default file extension
      parameters:
        - $ref: '#/components/parameters/quadkey'
        - $ref: '#/components/parameters/opacityPercentQueryString'
        - $ref: '#/components/parameters/opacityPercentHeader'
      responses:
        "200":
          $ref: '#/components/responses/TileResponse'
  /quadkey/{quadkey}.{extension}:
    get:
      tags:
        - Tile Requests
      summary: Return a non-root tile in the Quadkey tiling schema
      parameters:
        - $ref: '#/components/parameters/quadkey'
        - $ref: '#/components/parameters/extension'
        - $ref: '#/components/parameters/opacityPercentQueryString'
        - $ref: '#/components/parameters/opacityPercentHeader'
      responses:
        "200":
          $ref: '#/components/responses/TileResponse'
  /healthz:
    get:
      tags:
        - Health Check
      responses:
        "200":
          description: Healthy
