name: Validate and Test

on:
  push:
    branches:
      - '*'

jobs:
  test:
    name: Validate and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run
        run: scripts/run-tests-in-container.sh
